### PR TITLE
Update zepto-dnd.js

### PR DESCRIPTION
**Pull request by ChinuxParibus**
Line 381 commented
Now the dataTransfer object can use 'move' type of drag instead 'copy' natively

### CODE REVIEW

**Comment by rkusa** [comment]
Thanks for the PR! It seems that I had no reason to set this to `copy` explicitly. So this change should be fine. Have you already tested this change in all major browsers?

**Comment by ChinuxParibus** [comment]
I did! But only in Firefox 38 (and Firefox Aurora 40), Chrome 42 and Opera 20. Don't have more resources to test it. Sorry :cry:

**Comment by rkusa** [comment]
Thanks! Just wanted to know if I have to test FF and Chrome ;-) I'll merge it later today

**Comment by rkusa** [comment]
Could you please update your PR to remove this line instead of comment it out? Thanks

**Comment by ChinuxParibus** [comment]
I did... Good morning, have a nice weekend! :dancers:

**Comment by rkusa** [comment]
I think you've updated your master branch but not the `patch-1` branch ;-) Since changing the branch for a PR is not possible, you could either make a new PR from the master or update `patch-1` and squash the two commits together.

Thanks

**Comment by ChinuxParibus** [comment]
Sorry for the waiting... I did the update in the branch, but i'm brand new in Github's stuffs :crying_cat_face:

**Comment by rkusa** [comment]
No problem, thanks for the PR!

**Pull request merged**
